


<p>
<a class="btn btn-default" href="
    <?= $this->url('smsUsers', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus"></span> New User
</a>
</p>



<table class="table" id="uzivatele_online_table">
    <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Jméno</th>
            <th>Oddělení</th>
            <th>Email</th>
            <th>Telefon</th>
        </tr>
    </thead>

    <tbody id="uzivatele_online">

        <?php $pocitadlo = 1; ?>

        <?php /* @var $online \Application\Entity\UserSmsList */?>
        <?php foreach ($onlines as $online): ?>


            <tr>
                <th scope="row"><?= $pocitadlo ?>   </th>

                <td>
                    <?= $this->escapeHtml($online->getCeleJmeno()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getOddeleni()); ?>        
                </td>
                </td>
                <td>
                    <?= $this->escapeHtml($online->getEmail()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getTelefon()); ?>        
                </td>
            </tr>
            <?php $pocitadlo++; ?>   
        <?php endforeach; ?>        

    </tbody>
</table>