<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>


<p>
    <a class="btn btn-default" href="
       <?= $this->url('smsUsers', ['action' => 'pridejSmsUser']); ?>">
        <span class="glyphicon glyphicon-plus"></span> Přidat nového uživatele
    </a>
</p>



<table class="table" id="uzivatele_online_table">
    <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Jméno</th>
            <th>Oddělení</th>
            <th>Email</th>
            <th>Telefon</th>
        </tr>
    </thead>

    <tbody id="uzivatele_online">

        <?php $pocitadlo = 1; ?>

        <?php /* @var $online \Application\Entity\UserSmsList */ ?>
        <?php foreach ($onlines as $online): ?>


            <tr>
                <th scope="row"><?= $pocitadlo ?>   </th>

                <td>
                    <?= $this->escapeHtml($online->getCeleJmeno()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getOddeleni()); ?>        
                </td>
                </td>
                <td>
                    <?= $this->escapeHtml($online->getEmail()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getTelefon()); ?>        
                </td>
                <td>
                    </nobr>
                    <a class="btn btn-info" href="<?= $this->url('smsUsers', ['action' => 'upravSmsUser', 'id' => $online->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Upravit
                    </a>
                    <a class="btn btn-danger" href="<?= $this->url('smsUsers', ['action' => 'smazSmsUser', 'id' => $online->getId()]); ?>">
                        <span class="glyphicon glyphicon-remove"></span> Smazat
                    </a>
                    </nobr>
                </td>    
            </tr>
            <?php $pocitadlo++; ?>   
        <?php endforeach; ?>        

    </tbody>
</table>