<?php

$form = $this->form;

$form->get('cele_jmeno')->setAttributes([
            'class' => 'form-control form-control-lg',
            'placeholder' => 'Celé jméno',
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'col-sm-2 col-form-label col-form-label-lg'
        ]);

$form->get('oddeleni')->setAttributes([
            'class' => 'form-control form-control-lg',
            'placeholder' => 'Oddělení',
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'col-sm-2 col-form-label col-form-label-lg align-content-center'
        ]);

$form->get('email')->setAttributes([
            'class' => 'form-control form-control-lg',
            'placeholder' => 'E-mail',
            'required' => false,
            'autofocus' => false
        ])
        ->setLabelAttributes([
            'class' => 'col-sm-2 col-form-label col-form-label-lg'
        ]);

$form->get('telefon')->setAttributes([
            'class' => 'form-control form-control-lg',
            'placeholder' => 'Telefon',
            'required' => false,
        ])
        ->setLabelAttributes([
            'class' => 'col-sm-2 col-form-label col-form-label-lg'
        ]);


$form->prepare();
?>

<div class="container">

    <h2 class="form-signin-heading">Úprava uživatele</h2>
    <br/>

    <?php //<form name="signin-form" method="POST" class="col-9"> ?>
        
        <?= $this->form()->openTag($form); ?>

        <div class="form-group row">
            <?= $this->formLabel($form->get('cele_jmeno')); ?>
                <div class="col-lg-5">
                    <?= $this->formElement($form->get('cele_jmeno')); ?>
                </div>
        </div>

        <div class="form-group row">
            <?= $this->formLabel($form->get('oddeleni')); ?>
                <div class="col-lg-5">
                    <?= $this->formElement($form->get('oddeleni')); ?>
                </div>
        </div>        
        
        <div class="form-group row">
            
                <?= $this->formLabel($form->get('email')); ?>
            
            
                <div class="col-lg-5">
                    <?= $this->formElement($form->get('email')); ?>
                </div>
        </div>        
        
        <div class="form-group row">
            <?= $this->formLabel($form->get('telefon')); ?>
                <div class="col-lg-5">
                    <?= $this->formElement($form->get('telefon')); ?>
                </div>
        </div>                

        <div class="form-group row">
        </div>   
        <div class="form-group row">
        </div>   
        <div class="form-group row">
        </div>   
  

        <div class="form-group row offset-lg-2">
            <button class="btn btn-lg btn-primary btn-block col-lg-3 " type="submit">
                Uložit uživatele
            </button>
        </div>

    </form>
</div>
