<?php
$this->headTitle('Thank You');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1>Reset hesla</h1>

<?php if ($id=='sent'): ?>
<p>
    Link na reset hesla Vám byl zaslán na e-mail
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    Není tu žádný uživatel s tímto e-mailem
</p>
<?php elseif ($id=='set'): ?>
<p>
    Vaše heslo bylo úspěšně nastaveno
</p>
<p>
    Return to <a href="<?= $this->url('login'); ?>">Přihlašovací stránka</a>.
</p>
<?php elseif ($id=='failed'): ?>

Španý validační klíč nebo klíč vypršel. prosím opakujte    
 
    <a href="<?= $this->url('reset-password') ?>">ZDE</a> a pokuste se vyresetovat heslo ještě jednou
</p>
<?php endif; ?>
</div>
</div>    