<?php
$this->headTitle('Reset hesla');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Emailová adresa'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Resetovat Heslo</h2>

        <p>Vložte prosím Vaší emailovou adresu</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Vložte písmena která vidíte</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
