<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-11-17 20:06:04.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Application\Entity\Admin
 *
 * @ORM\Entity(repositoryClass="Application\Repository\AdminRepository")
 * @ORM\Table(name="Admins")
 */
class Admin
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id_admins;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    protected $jmeno;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $heslo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $umisteni;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    protected $telefon;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $cele_jmeno;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $last_online;

    /**
     * @ORM\OneToOne(targetEntity="Alert", mappedBy="admin")
     */
    protected $alert;

    /**
     * @ORM\OneToOne(targetEntity="Online", mappedBy="admin")
     */
    protected $online;

    public function __construct()
    {
        $this->alerts = new ArrayCollection();
        $this->onlines = new ArrayCollection();
    }

    /**
     * Set the value of id_admins.
     *
     * @param integer $id_admins
     * @return \Application\Entity\Admin
     */
    public function setIdAdmins($id_admins)
    {
        $this->id_admins = $id_admins;

        return $this;
    }

    /**
     * Get the value of id_admins.
     *
     * @return integer
     */
    public function getIdAdmins()
    {
        return $this->id_admins;
    }

    /**
     * Set the value of jmeno.
     *
     * @param string $jmeno
     * @return \Application\Entity\Admin
     */
    public function setJmeno($jmeno)
    {
        $this->jmeno = $jmeno;

        return $this;
    }

    /**
     * Get the value of jmeno.
     *
     * @return string
     */
    public function getJmeno()
    {
        return $this->jmeno;
    }

    /**
     * Set the value of heslo.
     *
     * @param string $heslo
     * @return \Application\Entity\Admin
     */
    public function setHeslo($heslo)
    {
        $this->heslo = $heslo;

        return $this;
    }

    /**
     * Get the value of heslo.
     *
     * @return string
     */
    public function getHeslo()
    {
        return $this->heslo;
    }

    /**
     * Set the value of umisteni.
     *
     * @param string $umisteni
     * @return \Application\Entity\Admin
     */
    public function setUmisteni($umisteni)
    {
        $this->umisteni = $umisteni;

        return $this;
    }

    /**
     * Get the value of umisteni.
     *
     * @return string
     */
    public function getUmisteni()
    {
        return $this->umisteni;
    }

    /**
     * Set the value of email.
     *
     * @param string $email
     * @return \Application\Entity\Admin
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of telefon.
     *
     * @param string $telefon
     * @return \Application\Entity\Admin
     */
    public function setTelefon($telefon)
    {
        $this->telefon = $telefon;

        return $this;
    }

    /**
     * Get the value of telefon.
     *
     * @return string
     */
    public function getTelefon()
    {
        return $this->telefon;
    }

    /**
     * Set the value of cele_jmeno.
     *
     * @param string $cele_jmeno
     * @return \Application\Entity\Admin
     */
    public function setCeleJmeno($cele_jmeno)
    {
        $this->cele_jmeno = $cele_jmeno;

        return $this;
    }

    /**
     * Get the value of cele_jmeno.
     *
     * @return string
     */
    public function getCeleJmeno()
    {
        return $this->cele_jmeno;
    }

    /**
     * Set the value of last_online.
     *
     * @param \DateTime $last_online
     * @return \Application\Entity\Admin
     */
    public function setLastOnline($last_online)
    {
        $this->last_online = $last_online;

        return $this;
    }

    /**
     * Get the value of last_online.
     *
     * @return \DateTime
     */
    public function getLastOnline()
    {
        return $this->last_online;
    }

    /**
     * Set Alert entity (one to one).
     *
     * @param \Application\Entity\Alert $alert
     * @return \Application\Entity\Admin
     */
    public function setAlert(Alert $alert = null)
    {
        $alert->setAdmin($this);
        $this->alert = $alert;

        return $this;
    }

    /**
     * Get Alert entity (one to one).
     *
     * @return \Application\Entity\Alert
     */
    public function getAlert()
    {
        return $this->alert;
    }

    /**
     * Set Online entity (one to one).
     *
     * @param \Application\Entity\Online $online
     * @return \Application\Entity\Admin
     */
    public function setOnline(Online $online = null)
    {
        $online->setAdmin($this);
        $this->online = $online;

        return $this;
    }

    /**
     * Get Online entity (one to one).
     *
     * @return \Application\Entity\Online
     */
    public function getOnline()
    {
        return $this->online;
    }

    public function __sleep()
    {
        return array('id_admins', 'jmeno', 'heslo', 'umisteni', 'email', 'telefon', 'cele_jmeno', 'last_online');
    }
}