<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-12-17 20:04:20.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Application\Entity\Migration
 *
 * @ORM\Entity(repositoryClass="Application\Repository\MigrationRepository")
 * @ORM\Table(name="migrations")
 */
class Migration
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255)
     */
    protected $version;

    public function __construct()
    {
    }

    /**
     * Set the value of version.
     *
     * @param string $version
     * @return \Application\Entity\Migration
     */
    public function setVersion($version)
    {
        $this->version = $version;

        return $this;
    }

    /**
     * Get the value of version.
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    public function __sleep()
    {
        return array('version');
    }
}