<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2018-01-04 07:21:48.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Application\Entity\RolePermission
 *
 * @ORM\Entity(repositoryClass="Application\Repository\RolePermissionRepository")
 * @ORM\Table(name="role_permission", indexes={@ORM\Index(name="IDX_6F7DF886D60322AC", columns={"role_id"}), @ORM\Index(name="IDX_6F7DF886FED90CCA", columns={"permission_id"})})
 */
class RolePermission
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $role_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $permission_id;

    /**
     * @ORM\ManyToOne(targetEntity="Role", inversedBy="rolePermissions")
     * @ORM\JoinColumn(name="role_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    protected $role;

    /**
     * @ORM\ManyToOne(targetEntity="Permission", inversedBy="rolePermissions")
     * @ORM\JoinColumn(name="permission_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    protected $permission;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Application\Entity\RolePermission
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of role_id.
     *
     * @param integer $role_id
     * @return \Application\Entity\RolePermission
     */
    public function setRoleId($role_id)
    {
        $this->role_id = $role_id;

        return $this;
    }

    /**
     * Get the value of role_id.
     *
     * @return integer
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     * Set the value of permission_id.
     *
     * @param integer $permission_id
     * @return \Application\Entity\RolePermission
     */
    public function setPermissionId($permission_id)
    {
        $this->permission_id = $permission_id;

        return $this;
    }

    /**
     * Get the value of permission_id.
     *
     * @return integer
     */
    public function getPermissionId()
    {
        return $this->permission_id;
    }

    /**
     * Set Role entity (many to one).
     *
     * @param \Application\Entity\Role $role
     * @return \Application\Entity\RolePermission
     */
    public function setRole(Role $role = null)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get Role entity (many to one).
     *
     * @return \Application\Entity\Role
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set Permission entity (many to one).
     *
     * @param \Application\Entity\Permission $permission
     * @return \Application\Entity\RolePermission
     */
    public function setPermission(Permission $permission = null)
    {
        $this->permission = $permission;

        return $this;
    }

    /**
     * Get Permission entity (many to one).
     *
     * @return \Application\Entity\Permission
     */
    public function getPermission()
    {
        return $this->permission;
    }

    public function __sleep()
    {
        return array('id', 'role_id', 'permission_id');
    }
}