<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-12-17 16:58:15.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Application\Entity\Session
 *
 * @ORM\Entity(repositoryClass="Application\Repository\SessionRepository")
 * @ORM\Table(name="Sessions")
 */
class Session
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=32)
     */
    protected $id_session;

    /**
     * @ORM\Column(type="integer")
     */
    protected $sess_expiry;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $sess_value;

    public function __construct()
    {
    }

    /**
     * Set the value of id_session.
     *
     * @param string $id_session
     * @return \Application\Entity\Session
     */
    public function setIdSession($id_session)
    {
        $this->id_session = $id_session;

        return $this;
    }

    /**
     * Get the value of id_session.
     *
     * @return string
     */
    public function getIdSession()
    {
        return $this->id_session;
    }

    /**
     * Set the value of sess_expiry.
     *
     * @param integer $sess_expiry
     * @return \Application\Entity\Session
     */
    public function setSessExpiry($sess_expiry)
    {
        $this->sess_expiry = $sess_expiry;

        return $this;
    }

    /**
     * Get the value of sess_expiry.
     *
     * @return integer
     */
    public function getSessExpiry()
    {
        return $this->sess_expiry;
    }

    /**
     * Set the value of sess_value.
     *
     * @param string $sess_value
     * @return \Application\Entity\Session
     */
    public function setSessValue($sess_value)
    {
        $this->sess_value = $sess_value;

        return $this;
    }

    /**
     * Get the value of sess_value.
     *
     * @return string
     */
    public function getSessValue()
    {
        return $this->sess_value;
    }

    public function __sleep()
    {
        return array('id_session', 'sess_expiry', 'sess_value');
    }
}