<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2018-01-10 21:50:38.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Application\Entity\UserSmsList
 *
 * @ORM\Entity(repositoryClass="Application\Repository\UserSmsListRepository")
 * @ORM\Table(name="userSmsList")
 */
class UserSmsList
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    protected $cele_jmeno;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $telefon;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $oddeleni;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $poznamka;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Application\Entity\UserSmsList
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of cele_jmeno.
     *
     * @param string $cele_jmeno
     * @return \Application\Entity\UserSmsList
     */
    public function setCeleJmeno($cele_jmeno)
    {
        $this->cele_jmeno = $cele_jmeno;

        return $this;
    }

    /**
     * Get the value of cele_jmeno.
     *
     * @return string
     */
    public function getCeleJmeno()
    {
        return $this->cele_jmeno;
    }

    /**
     * Set the value of email.
     *
     * @param string $email
     * @return \Application\Entity\UserSmsList
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of telefon.
     *
     * @param string $telefon
     * @return \Application\Entity\UserSmsList
     */
    public function setTelefon($telefon)
    {
        $this->telefon = $telefon;

        return $this;
    }

    /**
     * Get the value of telefon.
     *
     * @return string
     */
    public function getTelefon()
    {
        return $this->telefon;
    }

    /**
     * Set the value of oddeleni.
     *
     * @param string $oddeleni
     * @return \Application\Entity\UserSmsList
     */
    public function setOddeleni($oddeleni)
    {
        $this->oddeleni = $oddeleni;

        return $this;
    }

    /**
     * Get the value of oddeleni.
     *
     * @return string
     */
    public function getOddeleni()
    {
        return $this->oddeleni;
    }

    /**
     * Set the value of poznamka.
     *
     * @param string $poznamka
     * @return \Application\Entity\UserSmsList
     */
    public function setPoznamka($poznamka)
    {
        $this->poznamka = $poznamka;

        return $this;
    }

    /**
     * Get the value of poznamka.
     *
     * @return string
     */
    public function getPoznamka()
    {
        return $this->poznamka;
    }

    public function __sleep()
    {
        return array('id', 'cele_jmeno', 'email', 'telefon', 'oddeleni', 'poznamka');
    }
}