<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2018-01-04 07:21:48.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Application\Entity\UzivateleView
 *
 * @ORM\Entity(repositoryClass="Application\Repository\UzivateleViewRepository")
 * @ORM\Table(name="UzivateleViews")
 */
class UzivateleView
{
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $id_online;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $id_admins;

    /**
     * @ORM\Column(name="`status`", type="integer", nullable=true)
     */
    protected $status;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $cas_prihlaseni;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $cas_refresh;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $jmeno;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $heslo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $umisteni;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $telefon;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $cele_jmeno;

    public function __construct()
    {
    }

    /**
     * Set the value of id_online.
     *
     * @param integer $id_online
     * @return \Application\Entity\UzivateleView
     */
    public function setIdOnline($id_online)
    {
        $this->id_online = $id_online;

        return $this;
    }

    /**
     * Get the value of id_online.
     *
     * @return integer
     */
    public function getIdOnline()
    {
        return $this->id_online;
    }

    /**
     * Set the value of id_admins.
     *
     * @param integer $id_admins
     * @return \Application\Entity\UzivateleView
     */
    public function setIdAdmins($id_admins)
    {
        $this->id_admins = $id_admins;

        return $this;
    }

    /**
     * Get the value of id_admins.
     *
     * @return integer
     */
    public function getIdAdmins()
    {
        return $this->id_admins;
    }

    /**
     * Set the value of status.
     *
     * @param integer $status
     * @return \Application\Entity\UzivateleView
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the value of status.
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set the value of cas_prihlaseni.
     *
     * @param integer $cas_prihlaseni
     * @return \Application\Entity\UzivateleView
     */
    public function setCasPrihlaseni($cas_prihlaseni)
    {
        $this->cas_prihlaseni = $cas_prihlaseni;

        return $this;
    }

    /**
     * Get the value of cas_prihlaseni.
     *
     * @return integer
     */
    public function getCasPrihlaseni()
    {
        return $this->cas_prihlaseni;
    }

    /**
     * Set the value of cas_refresh.
     *
     * @param integer $cas_refresh
     * @return \Application\Entity\UzivateleView
     */
    public function setCasRefresh($cas_refresh)
    {
        $this->cas_refresh = $cas_refresh;

        return $this;
    }

    /**
     * Get the value of cas_refresh.
     *
     * @return integer
     */
    public function getCasRefresh()
    {
        return $this->cas_refresh;
    }

    /**
     * Set the value of jmeno.
     *
     * @param integer $jmeno
     * @return \Application\Entity\UzivateleView
     */
    public function setJmeno($jmeno)
    {
        $this->jmeno = $jmeno;

        return $this;
    }

    /**
     * Get the value of jmeno.
     *
     * @return integer
     */
    public function getJmeno()
    {
        return $this->jmeno;
    }

    /**
     * Set the value of heslo.
     *
     * @param integer $heslo
     * @return \Application\Entity\UzivateleView
     */
    public function setHeslo($heslo)
    {
        $this->heslo = $heslo;

        return $this;
    }

    /**
     * Get the value of heslo.
     *
     * @return integer
     */
    public function getHeslo()
    {
        return $this->heslo;
    }

    /**
     * Set the value of umisteni.
     *
     * @param integer $umisteni
     * @return \Application\Entity\UzivateleView
     */
    public function setUmisteni($umisteni)
    {
        $this->umisteni = $umisteni;

        return $this;
    }

    /**
     * Get the value of umisteni.
     *
     * @return integer
     */
    public function getUmisteni()
    {
        return $this->umisteni;
    }

    /**
     * Set the value of email.
     *
     * @param integer $email
     * @return \Application\Entity\UzivateleView
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return integer
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of telefon.
     *
     * @param integer $telefon
     * @return \Application\Entity\UzivateleView
     */
    public function setTelefon($telefon)
    {
        $this->telefon = $telefon;

        return $this;
    }

    /**
     * Get the value of telefon.
     *
     * @return integer
     */
    public function getTelefon()
    {
        return $this->telefon;
    }

    /**
     * Set the value of cele_jmeno.
     *
     * @param integer $cele_jmeno
     * @return \Application\Entity\UzivateleView
     */
    public function setCeleJmeno($cele_jmeno)
    {
        $this->cele_jmeno = $cele_jmeno;

        return $this;
    }

    /**
     * Get the value of cele_jmeno.
     *
     * @return integer
     */
    public function getCeleJmeno()
    {
        return $this->cele_jmeno;
    }

    public function __sleep()
    {
        return array('id_online', 'id_admins', 'status', 'cas_prihlaseni', 'cas_refresh', 'jmeno', 'heslo', 'umisteni', 'email', 'telefon', 'cele_jmeno');
    }
}