<?= $this->doctype() ?>

<html lang="cs">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Systém paniky v KKKV')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/signin.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('js/date.format.js'))
        ?>
    </head>

    <body>    



        <div class="col-md-12">
            <?php
            // Check if the activeMenuItemId passed to layout view model
            // and if so, use it for setting active navbar item.
            if (isset($activeMenuItemId)) {
                $this->mainMenu()->setActiveItemId($activeMenuItemId);
            }

            // Render the navbar
            echo $this->mainMenu()->render();
            ?>                
        </div>


        <?php
        /*
         *  Drobečková navigace
         *
         */
        /*
          <div class="row">
          <div class="col-md-12">
          <!-- Breadcrumbs -->
          <?php //$this->pageBreadcrumbs()->render(); ?>
          </div>
          </div>
         */
        ?>

        <?php
        // původně pro úspěšné phpUnit
        //<div class="container col-md-8 container jumbotron">
        ?>
        <div class="container col-md-8 jumbotron">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?><a target="_blank" href="https://www.martinmikac.cz/"> by Miki </a> </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>        

    </body>
</html>