<script>


    //setInterval( getData, 3000);


    //setInterval(getData, 3000);
    
    getData();
    
    function alertFunc() {
        //alert("Hello!");
    }

    function getData()
    {
        //alert("Hello");

        //$data = $this - > _request - > getPost();
        //        echo $id = $data['id'];
        //        echo $details = $data['details'];
        //this wont work;

        $.ajax({
            url: '/tutorial/ajax',
            type: 'POST',
            dataType: 'json',
            async: true,
            success: function (data, status) {
                var e = $('<tr><th>Author</th><th>Title</th><th>Picture</th></tr>');
                $('#book').html('');
                $('#book').append(e);
                for (i = 0; i < data.length; i++) {
                    book = data[i];
                    var e = $('<tr><td id = "author"></td><td id = "title"></td><td id="imagepath"><img src = ""/></td> < /tr>');
                    $('#author', e).html(book['author']);
                    $('#title', e).html(book['title']);
                    $('#imagepath img', e).attr('src', book['imagepath']);
                    $('#book').append(e);
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                alert('Ajax request failed.');
            }
        });
    }
    ;



</script>

<        div>
Přihláš             ení uživatelé
</div>

<h4    >        






</h4>




<?php foreach ($onlines as $online): ?>

<h3>
    <a href=            "#">
        <?php //echo $this->escapeHtml($online->getJmeno());  ?>
        <?php //echo $this->escapeHtml($online->getIdOnline()); ?>
    </a>    
</h3>

<?php endforeach; ?>


<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Jméno</th>
            <th>Oddělení</th>
            <th>Telefon</th>
            <th>Čas kontroly</th>
        </tr>
    </thead>

    <tbody>

        <?php $pocitadlo = 1; ?>


        <?php foreach ($onlines as $online): ?>


            <tr>
                <th scope="row"><?= $pocitadlo ?>   </th>

                <td>
                    <?= $this->escapeHtml($online->getCeleJmeno()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getUmisteni()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getTelefon()); ?>        
                </td>
                <td>
                    <?= $this->escapeHtml($online->getLastOnline()->format("d.m.Y H:i:s")) ?>
                </td>
            </tr>
            <?php $pocitadlo++; ?>   
        <?php endforeach; ?>        

    </tbody>
</table>
