<script>

        getAlert();
        setInterval(getAlert, 5000);
        var isSendedAlert = false;

        function getAlert()
        {
            $.ajax({
                url: '/check-alert',
                type: 'POST',
                dataType: 'json',
                async: true,
                success: function (data, status) {


                    //var body = document.body;
                    var div = document.createElement('div');
                    div.setAttribute("class", "badge-danger col-md-8");
                    div.setAttribute("id", "alert_div");
                    var tbl = document.createElement('table');
                    tbl.setAttribute("id", "alert_table");
                    //tbl.setAttribute("class", "badge-danger col-md-8");

                    var isVisible = false;
                    /*
                     echo " <p> ";
                     echo " <H3 style=\"color: red;\">Stiknuto tlačítko paniky!</H3> ";    		    
                     echo "<br/>";
                     echo "Jméno: ". $alert->cele_jmeno;
                     echo "<br/>";
                     echo "Kde: ". $alert->umisteni;
                     echo "<br/>";
                     echo "Telefon: ". $alert->telefon;
                     echo "<br/>";
                     */

                    var pocitadlo = 1;
                    for (i = 0; i < data.length; i++) {
                        alert = data[i];
                        var tr = tbl.insertRow();
                        var td = tr.insertCell();
                        var nadpis = document.createElement('H3');
                        nadpis.appendChild(document.createTextNode('Stiknuto tlačítko paniky!'));
                        td.appendChild(nadpis);
                        tr = tbl.insertRow();
                        var td = tr.insertCell();
                        td.appendChild(document.createTextNode('Jméno: ' + alert.user.setting.cele_jmeno));
                        tr = tbl.insertRow();
                        var td = tr.insertCell();
                        td.appendChild(document.createTextNode('Kde: ' + alert.user.setting.umisteni));
                        var dt_last_online = alert.cas_start.date;
                        var cas = dt_last_online.substr(0, dt_last_online.length - 7);
                        //var t = cas.split(/[- :]/);
                        //var d = new Date(Date.UTC(t[0], t[1] - 1, t[2], t[3], t[4], t[5]));
                        tr = tbl.insertRow();
                        var td = tr.insertCell();
                        td.appendChild(document.createTextNode('Kdy: ' + dateFormat(cas, "dd.mm.yyyy HH:MM:ss")));
                        tr = tbl.insertRow();
                        var td = tr.insertCell();
                        td.appendChild(document.createTextNode('telefon: ' + alert.user.setting.telefon));
                        tr = tbl.insertRow();
                        var td = tr.insertCell();
                        var form_1 = document.createElement('form');
                        form_1.setAttribute("name", "alertOver");
                        form_1.setAttribute("action", "<?= $this->url('alertOver') ?>/id/" + alert.id);
                        form_1.setAttribute("method", "POST");
                        var button_over = document.createElement('button');
                        button_over.setAttribute("class", "row btn btn-lg btn-primary btn-success btn-block col-lg offset-lg-0");
                        button_over.setAttribute("style", "margin-bottom: 20px; margin-top: 20px;");
                        button_over.setAttribute("type", "submit");
                        button_over.appendChild(document.createTextNode('Problém vyřešen'));
                        form_1.appendChild(button_over);
                        td.appendChild(form_1);
                        if (alert['isActive'] == true) {
                            isVisible = true;
                        }

                        pocitadlo++;
                    }

                    if (isVisible == true) {
                        var item = document.getElementById("alert_div");
                        if (item != null) {
                            item.parentNode.removeChild(item);
                        }



                        div.appendChild(tbl);
                        document.getElementById("active_alert").appendChild(div);
                        if (isSendedAlert == false) {
                            //alert('Stisknuto tláčítko paniky!!');
                            //confirm("Panika!!");
                            //alert("Panika!!")
                        }


                    } else {
                        var item = document.getElementById("alert_div");
                        if (item != null) {
                            item.parentNode.removeChild(item);
                        }
                    }

                    isVisible = false;
                    data = null;
                },
                error: function (xhr, textStatus, errorThrown) {
                    //alert('Ajax požadavek je chybný! Zavolejte na IT.');
                }
            });
        }




</script>
<h2>Zkontrolujte prosím, aplikaci panika.</h2>

<div id="active_alert" class="row align-items-center col-lg-7" style="margin-top: 20px; margin-bottom: 50px;"></div>

<?php

/* 
 * Zdrojový kód pouze pro interní potřebu Krajské knihovny Karlovy Vary.
 * @ Martin Mikač - 2017  * 
 */

